// ====================================================================================
// Data
// ====================================================================================

const versions = [
    { id: "base", name: "Base Game"},
    { id: "deluxe", name: "Deluxe Content Pack"},
    { id: "founder", name: "Founders Content Pack"},
    { id: "tecumseh_shawnee", name: "Tecumseh and Shawnee Pack"},
    { id: "napoleon", name: "Napoleon Pack"},
    { id: "persona_napoleon", name: "Persona Pack - Napoleon"},     
    { id: "crotw", name: "Crossroads of the World Collection"},
    { id: "rtr", name: "Right to Rule Collection"},
    { id: "top", name: "Tides of Power Collection"},
    { id: "brush_blade", name: "Brush and Blade Collection"},
]

const attributes = [
    { id: "c", name: "Cultural"},
    { id: "e", name: "Economic"},
    { id: "m", name: "Militaristic"},
    { id: "s", name: "Scientific"},
    { id: "d", name: "Diplomatic"},
    { id: "x", name: "Expansionist"},
    { id: "w", name: "Wildcard"}
]

const attributeColors = {
    "c": { color: "#ff69b4" },
    "e": { color: "#ffd700" },
    "m": { color: "#ff4444" },
    "s": { color: "#33b5e5" },
    "d": { color: "#9c27b0" },
    "x": { color: "#00C851" },
    "w": { style: "background: linear-gradient(90deg, #ff4444, #ff8c00, #ffd700, #00C851, #33b5e5, #9c27b0); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight: bold;" }
};

const ages = [
    { id: "ant", name: "Antiquity"},
    { id: "exp", name: "Exploration"},
    { id: "mod", name: "Modern"}
]

const civilizations = [
    { id: "achaemenid_persia", name: "Achaemenid Persia", attributes: ["e", "m"], age: "ant", game_version: "base"},
    { id: "aksumite", name: "Aksumite", attributes: ["c", "e"], age: "ant", game_version: "base"},
    { id: "assyrian", name: "Assyrian", attributes: ["m", "s"], age: "ant", game_version: "rtr"},
    { id: "carthaginian", name: "Carthaginian", attributes: ["m", "e"], age: "ant", game_version: "crotw"},
    { id: "eyptian", name: "Egyptian", attributes: ["c", "e"], age: "ant", game_version: "base"},
    { id: "greek", name: "Greek", attributes: ["c", "d"], age: "ant", game_version: "base"},
    { id: "han", name: "Han", attributes: ["d", "s"], age: "ant", game_version: "base"},
    { id: "heian_japanese", name: "Heian Japanese", attributes: ["c", "d"], age: "ant", game_version: "brush_blade"},
    { id: "khmer", name: "Khmer", attributes: ["x", "s"], age: "ant", game_version: "base"},
    { id: "mauryan", name: "Mauryan", attributes: ["m", "s"], age: "ant", game_version: "base"},
    { id: "maya", name: "Maya", attributes: ["c", "s"], age: "ant", game_version: "base"},
    { id: "mississippian", name: "Mississippian", attributes: ["e", "x"], age: "ant", game_version: "base"},
    { id: "roman", name: "Roman", attributes: ["c", "m"], age: "ant", game_version: "base"},
    { id: "silla_korea", name: "Silla Korean", attributes: ["d", "e"], age: "ant", game_version: "rtr"},
    { id: "tongan", name: "Tongan", attributes: ["d", "e"], age: "ant", game_version: "top"},
    { id: "abbasid", name: "Abbasid", attributes: ["x", "s"], age: "exp", game_version: "base"},
    { id: "bulgarian", name: "Bulgarian", attributes: ["x", "m"], age: "exp", game_version: "crotw"},
    { id: "chola", name: "Chola", attributes: ["d", "e"], age: "exp", game_version: "base"},
    { id: "goryeo", name: "Goryeo", attributes: ["c", "d"], age: "exp", game_version: "brush_blade"},
    { id: "hawaiian", name: "Hawaiian", attributes: ["c", "x"], age: "exp", game_version: "base"},
    { id: "icelandic", name: "Icelandic", attributes: ["c", "m"], age: "exp", game_version: "top"},
    { id: "incan", name: "Incan", attributes: ["e", "x"], age: "exp", game_version: "base"},    
    { id: "majapahit", name: "Majapahit", attributes: ["c", "x"], age: "exp", game_version: "base"},
    { id: "ming", name: "Ming", attributes: ["e", "s"], age: "exp", game_version: "base"},
    { id: "mongolian", name: "Mongolian", attributes: ["x", "m"], age: "exp", game_version: "base"},
    { id: "norman", name: "Norman", attributes: ["d", "m"], age: "exp", game_version: "base"},
    { id: "pirate", name: "Pirate", attributes: ["e", "m"], age: "exp", game_version: "top"},
    { id: "sengoku_japanese", name: "Sengoku Japanese", attributes: ["d", "m"], age: "exp", game_version: "brush_blade"},
    { id: "shawnee", name: "Shawnee", attributes: ["d", "e"], age: "exp", game_version: "tecumseh_shawnee"},
    { id: "songhai", name: "Songhai", attributes: ["e", "m"], age: "exp", game_version: "base"},
    { id: "spanish", name: "Spanish", attributes: ["e", "m"], age: "exp", game_version: "base"},
    { id: "vietnamese", name: "Vietnamese", attributes: ["c", "x"], age: "exp", game_version: "rtr"},
    { id: "american", name: "American", attributes: ["d", "e"], age: "mod", game_version:"base"},
    { id: "british", name: "British", attributes: ["e", "s"], age: "mod", game_version: "crotw"},
    { id: "bugandan", name: "Bugandan", attributes: ["c", "x"], age: "mod", game_version: "base"},
    { id: "french_imperial", name: "French Imperial", attributes: ["c", "d"], age: "mod", game_version: "base"},
    { id: "joseon", name: "Joseon", attributes: ["c", "x"], age: "mod", game_version: "brush_blade"},
    { id: "meiji_japanese", name: "Meiji Japanese", attributes: ["m", "s"], age: "mod", game_version: "base"},
    { id: "mexican", name: "Mexican", attributes: ["c", "d"], age: "mod", game_version: "base"},
    { id: "mughal", name: "Mughal", attributes: ["e", "x"], age: "mod", game_version: "base"},
    { id: "nepalese", name: "Nepalese", attributes: ["d", "c"], age: "mod", game_version: "crotw"},
    { id: "ottoman", name: "Ottoman", attributes: ["c", "m"], age: "mod", game_version: "top"},
    { id: "prussian", name: "Prussian", attributes: ["m", "d"], age: "mod", game_version: "base"},
    { id: "qajar", name: "Qajar", attributes: ["d", "x"], age: "mod", game_version: "rtr"},
    { id: "qing", name: "Qing", attributes: ["e", "x"], age: "mod", game_version: "base"},
    { id: "russian", name: "Russian", attributes: ["c", "s"], age: "mod", game_version: "base"},
    { id: "siamese", name: "Siamese", attributes: ["c", "d"], age: "mod", game_version: "base"},
];

const leaders = [
    { id: "ada_lovelace", name: "Ada Lovelace", attributes: ["c", "s"], game_version: "crotw"},
    { id: "alexander", name: "Alexander", attributes: ["c", "m"], game_version: "base"},
    { id: "amina", name: "Amina", attributes: ["e", "m"], game_version: "base"},
    { id: "ashoka_wc", name: "Ashoka, World Conqueror", attributes: ["d", "m"], game_version: "founder"},
    { id: "ashoka_wr", name: "Ashoka, World Renouncer", attributes: ["d", "x"], game_version: "base"},
    { id: "augustus", name: "Augustus", attributes: ["c", "x"], game_version: "base"},
    { id: "benjamin_franklin", name: "Benjamin Franklin", attributes: ["d", "s"], game_version: "base"},
    { id: "catherine", name: "Catherine the Great", attributes: ["c", "s"], game_version: "base"},
    { id: "charlemagne", name: "Charlemagne", attributes: ["m", "s"], game_version: "base"},
    { id: "confucius", name: "Confucius", attributes: ["x", "s"], game_version: "base"},
    { id: "edward_teach", name: "Edward Teach", attributes: ["m", "e"], game_version: "top"},
    { id: "friedrich_baroque", name: "Friedrich, Baroque", attributes: ["m", "c"], game_version: "deluxe"},
    { id: "friedrich_oblique", name: "Friedrich, Oblique", attributes: ["m", "s"], game_version: "base"},
    { id: "genghis_khan", name: "Genghis Khan", attributes: ["m", "x"], game_version: "rtr"},
    { id: "gilgamesh", name: "Gilgamesh", attributes: ["d", "m"], game_version: "base"},
    { id: "harriet_tubman", name: "Harriet Tubman", attributes: ["d", "m"], game_version: "base"},
    { id: "hatshepsut", name: "Hatshepsut", attributes: ["c", "e"], game_version: "base"},
    { id: "himiko_hs", name: "Himiko, High Shaman", attributes: ["c", "d"], game_version: "founder"},
    { id: "himiko_qw", name: "Himiko, Queen of Wa", attributes: ["d", "s"], game_version: "base"},
    { id: "ibn_battuta", name: "Ibn Battuta", attributes: ["x", "w"], game_version: "base"},
    { id: "isabella", name: "Isabella", attributes: ["e", "x"], game_version: "base"},
    { id: "jose_rizal", name: "José Rizal", attributes: ["c", "d"], game_version: "base"},
    { id: "lafayette", name: "Lafayette", attributes: ["c", "d"], game_version: "base"},
    { id: "lakshmibai", name: "Lakshmibai", attributes: ["m", "d"], game_version: "rtr"},
    { id: "machiavelli", name: "Machiavelli", attributes: ["d", "e"], game_version: "base"},
    { id: "napoleon_e", name: "Napoleon, Emperor", attributes: ["e", "d"], game_version: "napoleon"},
    { id: "napoleon_r", name: "Napoleon, Revolutionary", attributes: ["m", "c"], game_version: "persona_napoleon"},
    { id: "pachacuti", name: "Pachacuti", attributes: ["e", "x"], game_version: "base"},
    { id: "sayyida_al_hurra", name: "Sayyida al Hurra", attributes:["m", "d"], game_version: "top"},
    { id: "simon_bolivar", name: "Simón Bolívar", attributes: ["m", "x"], game_version: "crotw"},
    { id: "tecumseh", name: "Tecumseh", attributes: ["m", "d"], game_version: "tecumseh_shawnee"},
    { id: "toyotomi_hideyoshi", name: "Toyotomi Hideyoshi", attributes: ["c", "m"], game_version: "brush_blade"},
    { id: "trung_trac", name: "Trung Trac", attributes: ["m", "s"], game_version: "base"},
    { id: "xerxes_kk", name: "Xerxes, King of Kings", attributes: ["e", "m"], game_version: "base"},
    { id: "xerxes_a", name: "Xerxes, the Achaemenid", attributes: ["c", "e"], game_version: "deluxe"},
    { id: "yi_sun_sin", name: "Yi Sun-sin", attributes: ["m", "s"], game_version: "brush_blade"}
];

const historicalPairs = {
    "achaemenid_persia": ["xerxes_kk", "xerxes_a"],
    "american": ["benjamin_franklin", "harriet_tubman"],
    "british": ["ada_lovelace", "edward_teach"],
    "egyptian": ["hatshepsut"],
    "french_imperial": ["lafayette", "napoleon_e", "napoleon_r"],
    "greek": ["alexander"],
    "han": ["confucius"],
    "incan": ["pachacuti"],
    "joseon": ["yi_sun_sin"],
    "mauryan": ["ashoka_wc", "ashoka_wr"],
    "mongolian": ["genghis_khan"],
    "norman": ["charlemagne"],
    "pirate": ["edward_teach"],
    "prussian": ["friedrich_baroque", "friedrich_oblique"],
    "roman": ["augustus"],
    "russian": ["catherine"],
    "sengoku_japanese": ["toyotomi_hideyoshi"],
    "shawnee": ["tecumseh"],
    "spanish": ["isabella"],
};

const geograficalPairs = {
    "abbasid": ["gilgamesh", "ibn_battuta", "sayyida_al_hurra", "xerxes_kk", "xerxes_a"],
    "achaemenid_persia": ["xerxes_kk", "xerxes_a", "gilgamesh"],
    "aksumite": ["hatshepsut"],
    "american": ["benjamin_franklin", "harriet_tubman", "edward_teach", "tecumseh"],
    "assyrian": ["gilgamesh", "xerxes_kk", "xerxes_a", "ibn_battuta"],
    "british": ["ada_lovelace", "edward_teach", "augustus"],
    "bulgarian": ["alexander", "augustus", "catherine"],
    "carthaginian": ["augustus", "ibn_battuta", "sayyida_al_hurra"],
    "chola": ["ashoka_wc", "ashoka_wr", "lakshmibai"],
    "egyptian": ["hatshepsut", "augustus", "alexander"],
    "french_imperial": ["lafayette", "napoleon_e", "napoleon_r", "charlemagne", "augustus"],
    "goryeo": ["yi_sun_sin"],
    "greek": ["alexander", "augustus"],
    "han": ["confucius", "genghis_khan"],
    "heian_japanese": ["himiko_hs", "himiko_qw", "toyotomi_hideyoshi"],
    "icelandic": ["ada_lovelace"],
    "incan": ["pachacuti", "simon_bolivar"],
    "joseon": ["yi_sun_sin"],
    "khmer": ["trung_trac"],
    "mauryan": ["ashoka_wc", "ashoka_wr", "lakshmibai"],
    "meiji_japanese": ["himiko_hs", "himiko_qw", "toyotomi_hideyoshi"],
    "ming": ["confucius", "genghis_khan"],
    "mississippian": ["benjamin_franklin", "edward_teach", "harriet_tubman", "tecumseh"],
    "mongolian": ["genghis_khan", "catherine", "confucius"],
    "mughal": ["ashoka_wc", "ashoka_wr", "genghis_khan", "lakshmibai"],
    "nepalese": ["ashoka_wc", "ashoka_wr", "lakshmibai"],
    "norman": ["charlemagne", "augustus", "lafayette", "napoleon_e", "napoleon_r"],
    "ottoman": ["alexander", "augustus", "gilgamesh", "xerxes_kk", "xerxes_a", "ibn_battuta"],
    "pirate": ["edward_teach"],
    "prussian": ["friedrich_baroque", "friedrich_oblique", "catherine"],
    "qajar": ["genghis_khan", "gilgamesh", "xerxes_kk", "xerxes_a"],
    "qing": ["confucius", "genghis_khan"],
    "roman": ["augustus", "charlemagne", "isabella", "lafayette", "machiavelli", "napoleon_e", "napoleon_r", "alexander", "ibn_battuta", "hatshepsut", "sayyida_al_hurra"],
    "russian": ["catherine", "genghis_khan"],
    "sengoku_japanese": ["toyotomi_hideyoshi", "himiko_hs", "himiko_qw"],
    "shawnee": ["tecumseh", "benjamin_franklin", "harriet_tubman"],
    "siamese": ["trung_trac"],
    "songhai": ["amina"],
    "spanish": ["isabella", "augustus"],    
    "vietnamese": ["trung_trac"],    
};    

const strategicPairs = {
    "achaemenid_persia": ["friedrich_oblique", "simon_bolivar", "trung_trac", "xerxes_kk"],
    "aksumite": ["hatshepsut", "xerxes_a", "amina"],
    "assyrian": ["charlemagne", "friedrich_baroque", "genghis_khan", "trung_trac", "alexander"],       
    "carthaginian": ["augustus", "isabella", "sayyida_al_hurra", "hatshepsut", "edward_teach"],  
    "egyptian": ["alexander", "hatshepsut", "amina"],
    "greek": ["lafayette", "lakshmibai", "tecumseh", "himiko_hs"],
    "han": ["charlemagne", "confucius", "lafayette"],
    "heian_japanese": ["isabella"],
    "khmer": ["augustus", "pachacuti", "hatshepsut", "confucius", "ashoka_wr"],
    "mauryan": ["ashoka_wc", "ashoka_wr", "charlemagne", "himiko_hs", "jose_rizal"],
    "maya": ["ada_lovelace", "himiko_hs", "trung_trac"],
    "mississippian": ["xerxes_a", "hatshepsut", "amina"],
    "roman": ["augustus", "lafayette", "napoleon_r"],
    "silla_korea": ["xerxes_a", "himiko_qw", "gilgamesh", "amina"],
    "tongan": ["isabella", "tecumseh", "xerxes_a", "edward_teach", "sayyida_al_hurra"],
    "abbasid": ["pachacuti", "confucius", "ashoka_wr"],
    "bulgarian": ["edward_teach", "friedrich_baroque", "catherine"],
    "chola": ["sayyida_al_hurra", "xerxes_a"],
    "hawaiian": ["sayyida_al_hurra", "isabella", "edward_teach"],
    "icelandic": ["ada_lovelace", "catherine", "edward_teach", "friedrich_baroque", "isabella", "sayyida_al_hurra", "ibn_battuta"],
    "incan": ["pachacuti", "xerxes_a", "confucius", "ashoka_wr"],
    "majapahit": ["catherine", "confucius", "hatshepsut", "sayyida_al_hurra"],
    "ming": ["trung_trac", "lafayette", "friedrich_oblique", "confucius", "benjamin_franklin", "amina", "ada_lovelace"],
    "mongolian": ["amina", "ashoka_wc", "charlemagne", "genghis_khan", "napoleon_r", "simon_bolivar", "xerxes_kk"],
    "norman": ["sayyida_al_hurra", "lafayette", "genghis_khan", "charlemagne"],
    "pirate": ["edward_teach", "ibn_battuta", "isabella", "machiavelli"],
    "sengoku_japanese": ["trung_trac", "ghenghis_khan", "friedrich_oblique"],
    "shawnee": ["tecumseh", "lakshmibai", "hatshepsut", "catherine", "augustus", "amina"],
    "songhai": ["amina", "hatshepsut", "xerxes_a"],
    "spanish": ["isabella", "amina"],
    "vietnamese": ["trung_trac", "charlemagne"],
    "american": ["amina", "hatshepsut"],
    "british": ["sayyida_al_hurra", "isabella", "hatshepsut", "edward_teach", "augustus"],
    "bugandan": ["edward_teach", "hatshepsut", "sayyida_al_hurra"],
    "french_imperial": ["alexander", "ashoka_wc", "ashoka_wr", "charlemagne", "himiko_hs", "napoleon_r"],
    "meiji_japanese": ["trung_trac", "sayyida_al_hurra", "isabella", "friedrich_oblique", "edward_teach", "charlemagne", "benjamin_franklin"],
    "mexican": ["ada_lovelace", "ashoka_wc", "ashoka_wr", "catherine", "charlemagne", "himiko_hs", "jose_rizal", "lafayette"],
    "mughal": ["pachacuti", "isabella", "augustus", "alexander", "xerxes_kk"],
    "nepalese": ["benjamin_franklin", "gilgamesh", "himiko_qw", "lafayette", "machiavelli", "pachacuti"],
    "ottoman": ["xerxes_kk", "simon_bolivar", "napoleon_e", "friedrich_baroque", "catherine", "ashoka_wc", "toyotomi_hideyoshi"],
    "prussian": ["friedrich_oblique", "genghis_khan", "harriet_tubman", "napoleon_e", "napoleon_r", "simon_bolivar", "trung_trac", "xerxes_kk", "sayyida_al_hurra"],
    "qajar": ["xerxes_kk", "himiko_qw", "harriet_tubman", "gilgamesh", "benjamin_franklin"],
    "qing": ["amina", "confucius", "hatshepsut", "xerxes_a"],
    "russian": ["harriet_tubman", "catherine", "benjamin_franklin", "ada_lovelace"],
    "siamese": ["gilgamesh", "himiko_hs", "himiko_qw", "lakshmibai", "tecumseh"]
};