window.nameTranslations = window.nameTranslations || {};
window.nameTranslations.de = {
    versions: {
        "base": "Grundspiel",
        "deluxe": "Deluxe-Inhaltspaket",
        "founder": "Founders-Inhaltspaket",
        "tecumseh_shawnee": "Tecumseh- und Shawnee-Paket",
        "napoleon": "Napoleon-Paket",
        "persona_napoleon": "Persona-Pack - Napoleon",
        "crotw": "Crossroads of the World Sammlung",
        "rtr": "Right to Rule Sammlung",
        "top": "Tides of Power Sammlung"
    },
    attributes: {
        "c": "Kulturell",
        "e": "Wirtschaftlich",
        "m": "Militärisch",
        "s": "Wissenschaftlich",
        "d": "Diplomatisch",
        "x": "Expansionistisch",
        "w": "Wildcard"
    },
    ages: {
        "ant": "Antike",
        "exp": "Zeitalter der Entdeckung",
        "mod": "Moderne"
    },
    civ: {
        "achaemenid_persia": "Achämeniden-Persien",
        "aksumite": "Aksumitisches Reich",
        "assyrian": "Assyrisch",
        "carthaginian": "Karthaginisch",
        "eyptian": "Ägyptisch",
        "greek": "Griechisch",
        "han": "Han",
        "heian_japanese": "Heian-Japanisch",
        "khmer": "Khmer",
        "mauryan": "Maurya",
        "maya": "Maya",
        "mississippian": "Mississippian",
        "roman": "Römisch",
        "silla_korea": "Silla (Korea)",
        "tongan": "Tongaisch",
        "abbasid": "Abbasiden",
        "bulgarian": "Bulgarisch",
        "chola": "Chola",
        "hawaiian": "Hawaiianisch",
        "icelandic": "Isländisch",
        "incan": "Inka",
        "majapahit": "Majapahit",
        "ming": "Ming",
        "mongolian": "Mongolisch",
        "norman": "Normannisch",
        "pirate": "Pirat",
        "shawnee": "Shawnee",
        "songhai": "Songhai",
        "spanish": "Spanisch",
        "vietnamese": "Vietnamesisch",
        "american": "Amerikanisch",
        "british": "Britisch",
        "bugandan": "Buganda",
        "french_imperial": "Französisch (Imperial)",
        "meiji_japanese": "Meiji-Japanisch",
        "mexican": "Mexikanisch",
        "mughal": "Mogulreich",
        "nepalese": "Nepalesisch",
        "ottoman": "Osmanisch",
        "prussian": "Preußisch",
        "qajar": "Kadscharen",
        "qing": "Qing",
        "russian": "Russisch",
        "sengoku_japanese": "Sengoku-Japanisch",
        "siamese": "Siamesisch"
    },
    leader: {
        "ada_lovelace": "Ada Lovelace",
        "alexander": "Alexander",
        "amina": "Amina",
        "ashoka_wc": "Ashoka (Welteroberer)",
        "ashoka_wr": "Ashoka (Weltrenner)",
        "augustus": "Augustus",
        "benjamin_franklin": "Benjamin Franklin",
        "catherine": "Katharina die Große",
        "charlemagne": "Karl der Große",
        "confucius": "Konfuzius",
        "edward_teach": "Edward Teach",
        "friedrich_baroque": "Friedrich (Baroque)",
        "friedrich_oblique": "Friedrich (Oblique)",
        "genghis_khan": "Dschingis Khan",
        "gilgamesh": "Gilgamesch",
        "harriet_tubman": "Harriet Tubman",
        "hatshepsut": "Hatschepsut",
        "himiko_hs": "Himiko (High Shaman)",
        "himiko_qw": "Himiko (Queen of Wa)",
        "ibn_battuta": "Ibn Battuta",
        "isabella": "Isabella",
        "jose_rizal": "José Rizal",
        "lafayette": "Lafayette",
        "lakshmibai": "Lakshmibai",
        "machiavelli": "Machiavelli",
        "napoleon_e": "Napoleon (Kaiser)",
        "napoleon_r": "Napoleon (Revolutionär)",
        "pachacuti": "Pachacuti",
        "sayyida_al_hurra": "Sayyida al Hurra",
        "simon_bolivar": "Simón Bolívar",
        "tecumseh": "Tecumseh",
        "trung_trac": "Trung Trac",
        "xerxes_kk": "Xerxes, König der Könige",
        "xerxes_a": "Xerxes, der Achämenide"
    }
};
